name: Municipio E2E
inputs:
  sitemap-urls: 
    description: Sitemap URLs
    required: true
  timeout: 
    description: Timeout in minutes
    default: 60
    required: false

runs: 
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci

    - name: Setup testdata
      run: npm run test:setup-data

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30