name: Municipio E2E
inputs:
  sitemap-urls: 
    description: Sitemap URLs
    required: true
  timeout: 
    description: Timeout in minutes
    default: 60
    required: false
runs:
  using: docker
  image: mcr.microsoft.com/playwright:v1.49.0-noble
  args:
    - npx
    - playwright
    - test