name: 'Municipio E2E Tests'
description: 'Run Playwright E2E tests on a project'
author: 'Thor Brink'
inputs:
  sitemap_urls:
    description: 'Sitemap URLs for the test setup'
    required: true
  node_version:
    description: 'Version of Node.js to use'
    required: false
    default: '22'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install dependencies
      run: npm install

    - name: Build test fixtures
      env:
        SITEMAP_URLS: ${{ inputs.sitemap_urls }}
      run: npm run test:setup-data

    - name: Run Playwright tests
      run: npx playwright test
