name: Run Municipio E2E Tests sharded
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
        total-shards: [4]
    runs-on: ubuntu-latest
    steps:
      - name: Run Municipio E2E Tests
        uses: helsingborg-stad/municipio-e2e-action@dev
        with:
          sitemap-urls: 'https://raw.githubusercontent.com/helsingborg-stad/municipio-e2e-action/refs/heads/dev/fixtures/sitemap.xml'
          shard: ${{ matrix.shard }}
          total-shards: ${{ matrix.total-shards }}