name: Run Municipio E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
        shardTotal: [16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node.js modules and Playwright
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-playwright-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies and Playwright
        run: |
          npm ci &
          npx playwright install --with-deps chromium &
          wait
        shell: bash

      - name: Build test fixtures
 
