name: Run Municipio E2E Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Municipio E2E Tests
        uses: helsingborg-stad/municipio-e2e-action@dev
        with:
          sitemap-urls: 'https://visithelsingborg.hbgtest.se/sitemap.xml?pw_test='